name: pseor
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - scipy
  - astromatic-source-extractor
  - astropy
  - astropy-healpix
  - matplotlib
  - pandas
  - pip
  - python=3.9.*
  - tqdm 
  - pip:
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astropy-healpix==0.7
      - asttokens==2.2.1
      - asyncssh==2.13.1
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blosc2==2.0.0
      - casa-formats-io==0.2.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - comm==0.1.3
      - configparser==5.3.0
      - contourpy==1.0.7
      - corner==2.2.2
      - cosmospectra==0.1.1
      - cryptography==40.0.2
      - cython==0.29.34
      - dask==2023.5.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dynesty==1.2.3
      - emcee==3.1.4
      - executing==1.2.0
      - fast-histogram==0.9
      - fastjsonschema==2.16.3
      - fonttools==4.39.4
      - fqdn==1.5.1
      - fsspec==2023.5.0
      - gpy==1.10.0
      - h5py==3.8.0
      - healpy==1.16.2
      - imageio==2.31.1
      - importlib-metadata==6.6.0
      - iniconfig==2.0.0
      - ipykernel==6.23.1
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - lazy-loader==0.2
      - libpipe==0.3
      - llvmlite==0.40.1
      - locket==1.0.0
      - markupsafe==2.1.2
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - msgpack==1.0.5
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numba==0.57.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - packaging==23.1
      - pandocfilters==1.5.0
      - paramz==0.9.5
      - parso==0.8.3
      - partd==1.4.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - pluggy==1.2.0
      - progressbar2==4.2.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - ps-eor==0.28
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyerfa==2.0.0.3
      - pyfftw==0.13.1
      - pygments==2.15.1
      - pyrsistent==0.19.3
      - pytest==7.4.0
      - python-json-logger==2.0.7
      - python-utils==3.5.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - radio-beam==0.3.4
      - reproject==0.10.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spectral-cube==0.6.0
      - stack-data==0.6.2
      - tables==3.8.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - tools21cm==2.0.2
      - toolz==0.12.0
      - torch==1.13.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - ultranest==3.5.7
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.7
      - zipp==3.15.0
