workflow_steps_notebooks:
  - workflow/create_mask/pipeline.ipynb
  - workflow/create_mask/mask.ipynb
  - workflow/pca_substraction/PCA_data_SDC3.ipynb
  # - workflow/polynomial_fit/PolyFit.py
  - workflow/power_spectrum/processing.ipynb
  - workflow/power_spectrum/ps_estimation.ipynb

paths:
  data_cube: '/mnt/sdc3a.MS.0/sdc3dataset/Image/ZW3.msw_image.fits'


